<a href="https://colab.research.google.com/github/luisferdm6/02_analisis_hotelero_pandas/blob/main/01_limpieza_y_agrupaciones_hotel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url_dataset = "https://raw.githubusercontent.com/Rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv"

df_real = pd.read_csv(url_dataset)

df_real.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [2]:
df_real.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [3]:
df_real.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [4]:
df_real ['children'] = df_real ['children'].fillna(0)

df_real ['children'].isnull().sum()

np.int64(0)

In [5]:
df_real = df_real.drop(columns=['company'], errors='ignore')

'company' in df_real.columns

False

In [6]:
df_real ['country'] = df_real ['country'].fillna('Unknown')

df_real ['country'].isnull().sum()

np.int64(0)

In [7]:
df_real ['agent'] = df_real ['agent'].fillna(0)

df_real ['agent'].isnull().sum()

np.int64(0)

In [8]:
df_real ['children'] = df_real ['children'].astype(int)

df_real ['agent'] = df_real ['agent'].astype(int)

df_real [['children', 'agent']].head()

   children  agent
0         0      0
1         0      0
2         0      0
3         0    304
4         0    240

In [9]:
df_real ['is_canceled'].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [10]:
df_real ['is_canceled'].value_counts(normalize=True) * 100

is_canceled
0    62.958372
1    37.041628
Name: proportion, dtype: float64

In [11]:
df_real.groupby('hotel') ['adr'].mean()

hotel
City Hotel      105.304465
Resort Hotel     94.952930
Name: adr, dtype: float64

In [12]:
df_sin_unknown = df_real[df_real['country'] != 'Unknown']

df_sin_unknown['country'].value_counts(normalize=True).map('{:.2%}'.format).head()

country
PRT    40.87%
GBR    10.20%
FRA     8.76%
ESP     7.21%
DEU     6.13%
Name: proportion, dtype: object

In [13]:
df_real.groupby('is_canceled') ['lead_time'].mean()

is_canceled
0     79.984687
1    144.848815
Name: lead_time, dtype: float64

In [14]:
df_real.groupby('deposit_type') ['is_canceled'].mean() * 100

deposit_type
No Deposit    28.377022
Non Refund    99.362446
Refundable    22.222222
Name: is_canceled, dtype: float64

In [15]:
df_real['reservation_status_date'] = pd.to_datetime(df_real['reservation_status_date'])

In [16]:
df_real['reservation_status_date'].dtype

dtype('<M8[ns]')

In [17]:
df_real['status_year'] = df_real['reservation_status_date'].dt.year

In [18]:
df_real[['reservation_status_date','status_year']].head()

  reservation_status_date  status_year
0              2015-07-01         2015
1              2015-07-01         2015
2              2015-07-02         2015
3              2015-07-02         2015
4              2015-07-03         2015

In [19]:
df_real['status_day_name'] = df_real['reservation_status_date'].dt.day_name()

df_real['status_day_name'].value_counts(normalize=True).map('{:.2%}'.format)

status_day_name
Monday       15.66%
Friday       15.47%
Thursday     15.19%
Wednesday    15.03%
Tuesday      14.01%
Sunday       13.81%
Saturday     10.83%
Name: proportion, dtype: object

In [20]:
#¿El lunes tiene más registros simplemente porque hay más salidas (Check-out), o es el día en que la gente MÁS CANCELA?

df_real.groupby('status_day_name')['is_canceled'].mean().map('{:.2%}'.format)

status_day_name
Friday       40.50%
Monday       43.18%
Saturday     23.68%
Sunday       16.13%
Thursday     38.91%
Tuesday      46.37%
Wednesday    45.34%
Name: is_canceled, dtype: object

In [21]:
#¿Cuál es la tarifa promedio por noche según el tipo de hotel?

df_real.groupby('hotel')['adr'].mean().map('${:.2f}'.format)

hotel
City Hotel      $105.30
Resort Hotel     $94.95
Name: adr, dtype: object

In [22]:
#¿Cuál es la tarifa promedio por noche dividida por tipo de hotel. Y al mismo tiempo por si la reserva fue cancelada o no?

df_real['is_canceled'] = df_real['is_canceled'].map({0: 'No', 1: 'Yes'})

df_real.groupby(['hotel','is_canceled'])['adr'].mean().map('${:.2f}'.format).reset_index()

          hotel is_canceled      adr
0    City Hotel          No  $105.75
1    City Hotel         Yes  $104.69
2  Resort Hotel          No   $90.79
3  Resort Hotel         Yes  $105.79

In [23]:
df_ordenado = df_real.groupby('market_segment')['adr'].mean().reset_index().sort_values(by='adr', ascending=False)

df_ordenado['adr'] = df_ordenado['adr'].map('${:.2f}'.format)

df_ordenado

  market_segment      adr
6      Online TA  $117.20
3         Direct  $115.45
0       Aviation  $100.14
5  Offline TA/TO   $87.35
4         Groups   $79.48
2      Corporate   $69.36
7      Undefined   $15.00
1  Complementary    $2.89

In [24]:
#¿Cuál es el rango real de precios (piso, promedio y techo) al que estamos vendiendo en cada canal comercial, y qué tan rentable es cada canal?

resumen_tarifas = df_real.groupby('market_segment')['adr'].agg(['min','mean','max']).reset_index()

resumen_tarifas = resumen_tarifas.sort_values(by='mean',ascending=False)

resumen_tarifas[['min','mean','max']] = resumen_tarifas[['min','mean','max']].map('${:.2f}'.format)

resumen_tarifas

  market_segment     min     mean       max
6      Online TA   $0.00  $117.20   $450.00
3         Direct   $0.00  $115.45   $451.50
0       Aviation   $0.00  $100.14   $193.50
5  Offline TA/TO   $0.00   $87.35  $5400.00
4         Groups  $-6.38   $79.48   $367.00
2      Corporate   $0.00   $69.36   $508.00
7      Undefined  $12.00   $15.00    $18.00
1  Complementary   $0.00    $2.89   $170.00

In [25]:
#Detectando anomalias

df_real[df_real['adr'] > 5000][['hotel', 'is_canceled', 'reserved_room_type', 'adults', 'children', 'adr']]

            hotel is_canceled reserved_room_type  adults  children     adr
48515  City Hotel         Yes                  A       2         0  5400.0

In [26]:
df_real[df_real['adr'] < 0][['hotel', 'is_canceled', 'reserved_room_type', 'adults', 'children', 'adr']]

              hotel is_canceled reserved_room_type  adults  children   adr
14969  Resort Hotel          No                  A       2         0 -6.38

In [27]:
df_real = df_real[(df_real['adr'] >= 0) & (df_real['adr'] < 5000)]

df_real.shape

(119388, 33)

In [28]:
#Comprobación de corrección de anomalías

resumen_limpio = df_real.groupby('market_segment')['adr'].agg(['min','mean','max']).reset_index()

resumen_limpio = resumen_limpio.sort_values(by='mean',ascending=False)

resumen_limpio[['min','mean','max']] = resumen_limpio[['min','mean','max']].map('${:.2f}'.format)

resumen_limpio

  market_segment     min     mean      max
6      Online TA   $0.00  $117.20  $450.00
3         Direct   $0.00  $115.45  $451.50
0       Aviation   $0.00  $100.14  $193.50
5  Offline TA/TO   $0.00   $87.14  $510.00
4         Groups   $0.00   $79.48  $367.00
2      Corporate   $0.00   $69.36  $508.00
7      Undefined  $12.00   $15.00   $18.00
1  Complementary   $0.00    $2.89  $170.00

In [29]:
#¿Cuánto tiempo se queda realmente un huésped en cada tipo de hotel y qué perfil de viaje (de paso, negocios o vacaciones) domina cada propiedad?

df_real['total_stay'] = df_real['stays_in_week_nights'] + df_real['stays_in_weekend_nights']

df_real.groupby('hotel')['total_stay'].agg(['min','mean','max']).reset_index()

          hotel  min      mean  max
0    City Hotel    0  2.978167   57
1  Resort Hotel    0  4.318405   69

In [30]:
#¿Cuánto dinero real en ingresos por habitación generó cada hotel con las estancias efectivas (no canceladas)?

df_real['total_cost'] = df_real['total_stay'] * df_real['adr']

ingresos_hotel = df_real[df_real['is_canceled'] == 'No'].groupby('hotel')['total_cost'].sum().reset_index()

ingresos_hotel['total_cost'] = ingresos_hotel['total_cost'].map('${:,.2f}'.format)

ingresos_hotel

          hotel      total_cost
0    City Hotel  $14,394,410.18
1  Resort Hotel  $11,601,914.03

In [32]:
#¿Cuál de los dos hoteles tiene una fuga financiera más grave por cancelaciones?

ingresos_perdidos = df_real[df_real['is_canceled'] == 'Yes'].groupby('hotel')['total_cost'].sum().reset_index()

ingresos_perdidos['total_cost'] = ingresos_perdidos['total_cost'].map('${:,.2f}'.format)

ingresos_perdidos

          hotel      total_cost
0    City Hotel  $10,879,659.78
1  Resort Hotel   $5,842,177.34

In [34]:
#¿Qué porcentaje exacto de todas las reservas recibidas termina en cancelación en cada hotel?

df_real['cancelada_num'] = df_real['is_canceled'] == 'Yes'

tasa_cancelacion = df_real.groupby('hotel')['cancelada_num'].mean().map('{:.2%}'.format).reset_index()

tasa_cancelacion

          hotel cancelada_num
0    City Hotel        41.73%
1  Resort Hotel        27.76%

In [35]:
#Ya sabemos que el City Hotel tiene un 41.73% de cancelaciones. Pero, ¿a través de qué canal comercial están llegando los clientes más informales y canceladores?

tasa_segmento = df_real.groupby('market_segment')['cancelada_num'].mean().sort_values(ascending=False).map('{:.2%}'.format).reset_index()

tasa_segmento

  market_segment cancelada_num
0      Undefined       100.00%
1         Groups        61.07%
2      Online TA        36.72%
3  Offline TA/TO        34.31%
4       Aviation        21.94%
5      Corporate        18.73%
6         Direct        15.34%
7  Complementary        13.06%

In [37]:
#¿Cuántas reservas totales tenía realmente el canal Undefined que marcaba 100%?

#¿Cuál es el canal que aporta el mayor volumen de clientes al hotel?

total_reservas = df_real.groupby('market_segment').agg(
    total_reservas = ('is_canceled','count'),
    cancelaciones = ('cancelada_num','sum'),
    tasa_cancelacion = ('cancelada_num','mean')
).reset_index()

total_reservas = total_reservas.sort_values(by='total_reservas',ascending=False)

total_reservas['tasa_cancelacion'] = total_reservas['tasa_cancelacion'].map('{:.2%}'.format)

total_reservas

  market_segment  total_reservas  cancelaciones tasa_cancelacion
6      Online TA           56477          20739           36.72%
5  Offline TA/TO           24218           8310           34.31%
4         Groups           19810          12097           61.07%
3         Direct           12606           1934           15.34%
2      Corporate            5295            992           18.73%
1  Complementary             743             97           13.06%
0       Aviation             237             52           21.94%
7      Undefined               2              2          100.00%

In [41]:
#¿Con cuántos días de anticipación reservan las personas que sí se quedan a dormir en comparación con las que terminan cancelando?

anticipacion_cancelacion = df_real.groupby('is_canceled')['lead_time'].agg(['mean','median']).reset_index()

anticipacion_cancelacion

  is_canceled        mean  median
0          No   79.983157    45.0
1         Yes  144.851299   113.0

In [42]:
#Si los clientes reservan con 4 meses de anticipación y cancelan de forma masiva... ¿por qué se dan ese lujo sin temor a perder dinero? ¿Qué tipo de garantía o anticipo les estamos pidiendo?

resumen_deposito = df_real.groupby('deposit_type').agg(
    total_reservas = ('is_canceled','count'),
    cancelaciones = ('cancelada_num','sum'),
    tasa_cancelacion = ('cancelada_num','mean')
).sort_values(by='total_reservas', ascending=False).reset_index()

resumen_deposito['tasa_cancelacion'] = resumen_deposito['tasa_cancelacion'].map('{:.2%}'.format)

resumen_deposito

  deposit_type  total_reservas  cancelaciones tasa_cancelacion
0   No Deposit          104640          29694           28.38%
1   Non Refund           14586          14493           99.36%
2   Refundable             162             36           22.22%

In [45]:
#¿Los clientes recurrentes (huéspedes que ya nos conocen y han visitado el hotel antes) son más confiables que los clientes primerizos? ¿Qué tasa de cancelación tiene cada grupo?

resumen_lealtad = df_real.groupby('is_repeated_guest').agg(
    total_reservas = ('is_canceled','count'),
    cancelaciones = ('cancelada_num','sum'),
    tasa_cancelacion = ('cancelada_num','mean')
).reset_index()

resumen_lealtad['is_repeated_guest'] = resumen_lealtad['is_repeated_guest'].map({0 : 'No', 1 : 'Yes'})

resumen_lealtad['tasa_cancelacion'] = resumen_lealtad['tasa_cancelacion'].map('{:.2%}'.format)

resumen_lealtad

  is_repeated_guest  total_reservas  cancelaciones tasa_cancelacion
0                No          115579          43671           37.78%
1               Yes            3809            552           14.49%